# примеры API-запросов

@baseUrl = http://localhost:5000

# создание объявления
POST {{baseUrl}}/ads/
Content-Type: application/json

{
  "head": "Fish2",
  "username": 2
}

###

# получение объявления
GET {{baseUrl}}/ads/1
Content-Type: application/json

###

# обновление объявления
PATCH {{baseUrl}}/ads/1
Content-Type: application/json

{
  "head": "2"
}

###

# удаление объявления
DELETE {{baseUrl}}/ads/2
Content-Type: application/json

###

# создание пользователя
POST {{baseUrl}}/user/
Content-Type: application/json

{
  "email": "anapa@1.ru",
  "password": "1234"
  
}

###

# получение пользователя
GET {{baseUrl}}/user/1/
Content-Type: application/json

###

# изменение пользователя
PATCH {{baseUrl}}/user/1/
Content-Type: application/json

{
  "email": "anapa@1.com",
  "password": "12344321"
  
}

###

# удаление пользователя
DELETE {{baseUrl}}/user/1
Content-Type: application/json