# примеры API-запросов

@baseUrl = http://localhost:5000

# создание объявления
POST {{baseUrl}}/ads/
Content-Type: application/json

{
  "head": "Motok",
  "description": "Best cat",
  "username": "sochi@ya.ru",
  "password": "87654321"
}

###

# получение объявления
GET {{baseUrl}}/ads/3
Content-Type: application/json

###

# обновление объявления
PATCH {{baseUrl}}/ads/3
Content-Type: application/json

{
  "head": "4",
  "description": "4",
  "username": "sochi@ya.ru",
  "password": "87654321"
}

###

# удаление объявления
DELETE {{baseUrl}}/ads/2
Content-Type: application/json

{
  "username": "a4@ya.ru",
  "password": "12345678"
}

###

# создание пользователя
POST {{baseUrl}}/user/
Content-Type: application/json

{
  "email": "sochi@ya.ru",
  "password": "87654321"
  
}

###

# получение пользователя
GET {{baseUrl}}/user/1/
Content-Type: application/json

###

# изменение пользователя
PATCH {{baseUrl}}/user/1/
Content-Type: application/json

{
  "email": "sochi3@ya.ru",
  "password": "12345678"
  
}
